---
- name: Install and start web
  hosts: web
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: present
    - name: Pusg index.html
      copy:
        src: /home/admin/project/index.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644
    - name: start httpd service
      service:
        name: httpd
        state: started
        enabled: true
