---
- name: Deploy and start Apache  httpd server
  hosts: web
  vars:
    web_pkg : httpd
    firewall_pkg: firewalld
    web_service: httpd
    firewall_service: firewalld
    rule: http
  tasks:
    - name: Install package
      yum:
        name:
         - "{{ web_pkg }}"
         - "{{ firewall_pkg }}"
        state: latest
    - name: start and Enable firewall  service
      service:
        name: "{{ firewall_pkg }}"
        state: started
        enabled: true
    - name: start and enable web service
      service:
        name: "{{ web_pkg }}"
        state: started
        enabled: true
    - name: push file
      copy:
        src: /home/admin/project/playbooks
        dest: /var/www/html/index.html

    - name: open firewall port
      firewalld:
        service: "{{ rule }}"
        permanent: true
        immediate: true
        state: enabled


- name: varify Web service
  hosts: localhost
  become: false
  tasks:
    - name: testing web server
      uri:
        url: http://192.168.31.160
        status_code: 200

